import 'package:flutter/material.dart';

List<int> fibers = [1, 2, 4, 8, 12, 16, 20, 24];

Map<String, List<Color>> fiberColors = {
  'DIN/VDE 08888': [
    Colors.red,
    Colors.green,
    Colors.blue,
    Colors.yellow,
    Colors.white,
    Colors.grey,
    Colors.brown,
    Colors.purple,
    Colors.cyanAccent,
    Colors.black,
    Colors.orange,
    Colors.pink[200]!,
    Colors.red,
    Colors.green,
    Colors.blue,
    Colors.yellow,
    Colors.white,
    Colors.grey,
    Colors.brown,
    Colors.purple,
    Colors.cyanAccent,
    Colors.black,
    Colors.orange,
    Colors.pink[200]!
  ],
  'SNR': [
    Colors.blue,
    Colors.orange,
    Colors.green,
    Colors.brown,
    Colors.grey,
    Colors.white,
    Colors.red,
    Colors.black,
    Colors.yellow,
    Colors.purple,
    Colors.pink[200]!,
    Colors.cyan[100]!,
    Colors.blue,
    Colors.orange,
    Colors.green,
    Colors.brown,
    Colors.grey,
    Colors.white,
    Colors.red,
    Colors.black,
    Colors.yellow,
    Colors.purple,
    Colors.pink[200]!,
    Colors.cyan[100]!,
  ]
};
